{
 "title": "Pods",
 "time": { "from": "2024-09-05T16:47:00.926Z", "to": "2024-09-05T17:07:00.926Z" },
 "panels": [
  {
   "title": "ram (megabytes)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=\"default\", pod!=\"\", container!=\"\"}) by (pod) / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu(mcores)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=\"default\", pod!=\"\", container!=\"\"}[5m])) by (pod) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "cpu nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(node_cpu_seconds_total{mode!=\"idle\"}[5m])) by (instance) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) by (instance) / (1024 * 1024)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}