apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-1-depl
  labels:
    app: ms-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ms-1
  template:
    metadata:
      name: ms-1-depl
      labels:
        app: ms-1
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"
      containers:
        - name: ms-1
          image: madd47emz/pfe-microservices:ms1
          imagePullPolicy: Always
          ports:
            - containerPort: 8090
              protocol: TCP
      restartPolicy: Always
      
