apiVersion: v1
kind: Service
metadata:
  name: ms-2-srv
spec:
  selector:
    app: ms-2
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091
  type: NodePort
  externalTrafficPolicy: Local #to prevent fowarding request to other pods in another nodes
  
