apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-3-depl
  labels:
    app: ms-3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-3
  template:
    metadata:
      name: ms-3-depl
      labels:
        app: ms-3
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: "worker"
      containers:
        - name: ms-3
          image: madd47emz/pfe-microservices:ms3
          imagePullPolicy: Always
          ports:
            - containerPort: 8092
              protocol: TCP
      restartPolicy: Always
      
