apiVersion: v1
kind: Service
metadata:
  name: ms-3-srv
spec:
  selector:
    app: ms-3
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092
  type: NodePort
  externalTrafficPolicy: Local #to prevent fowarding request to other pods in another nodes
  
